import {
    LayoutDashboard,
    FileText,
    List,
    PlusCircle,
    File,
    Database,
    Users,
    Package,
    CreditCard,
    Settings,
    HelpCircle,
    ChevronDown,
    ChevronRight,
    Sun,
    Moon,
    LogOut,
    MoreVertical,
    Briefcase,
    Tag,
    Clock,
    Shield,
    Globe,
    ArrowLeft,
    Search,
    Bell,
    MessageCircle,
    Plus
} from 'lucide-react';

export const ICON_MAP: Record<string, any> = {
    'dashboard': LayoutDashboard,
    'cases': FileText,
    'list': List,
    'plus': Plus, // Changed from PlusCircle to Plus generic
    'plus-circle': PlusCircle,
    'file': File,
    'database': Database,
    'users': Users,
    'package': Package,
    'billing': CreditCard,
    'settings': Settings,
    'help-circle': HelpCircle,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    'sun': Sun,
    'moon': Moon,
    'logout': LogOut,
    'more': MoreVertical,
    'briefcase': Briefcase,
    'tag': Tag,
    'clock': Clock,
    'shield': Shield,
    'globe': Globe,
    'arrow-left': ArrowLeft,
    'search': Search,
    'bell': Bell,
    'message': MessageCircle
};
