// Common EU countries first, then alphabetically
export const COUNTRIES = [
  { code: "DE", name: "Deutschland" },
  { code: "AT", name: "Österreich" },
  { code: "CH", name: "Schweiz" },
  { code: "FR", name: "Frankreich" },
  { code: "IT", name: "Italien" },
  { code: "NL", name: "Niederlande" },
  { code: "BE", name: "Belgien" },
  { code: "PL", name: "Polen" },
  { code: "CZ", name: "Tschechien" },
  { code: "ES", name: "Spanien" },
  { code: "GB", name: "Vereinigtes Königreich" },
  { code: "US", name: "USA" },
  { code: "CN", name: "China" },
  // Additional countries
  { code: "AD", name: "Andorra" },
  { code: "AE", name: "Vereinigte Arabische Emirate" },
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albanien" },
  { code: "AM", name: "Armenien" },
  { code: "AR", name: "Argentinien" },
  { code: "AU", name: "Australien" },
  { code: "BA", name: "Bosnien und Herzegowina" },
  { code: "BG", name: "Bulgarien" },
  { code: "BR", name: "Brasilien" },
  { code: "CA", name: "Kanada" },
  { code: "DK", name: "Dänemark" },
  { code: "EE", name: "Estland" },
  { code: "FI", name: "Finnland" },
  { code: "GR", name: "Griechenland" },
  { code: "HR", name: "Kroatien" },
  { code: "HU", name: "Ungarn" },
  { code: "IE", name: "Irland" },
  { code: "IL", name: "Israel" },
  { code: "IN", name: "Indien" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "Südkorea" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Litauen" },
  { code: "LU", name: "Luxemburg" },
  { code: "LV", name: "Lettland" },
  { code: "ME", name: "Montenegro" },
  { code: "MK", name: "Nordmazedonien" },
  { code: "MT", name: "Malta" },
  { code: "MX", name: "Mexiko" },
  { code: "NO", name: "Norwegen" },
  { code: "NZ", name: "Neuseeland" },
  { code: "PT", name: "Portugal" },
  { code: "RO", name: "Rumänien" },
  { code: "RS", name: "Serbien" },
  { code: "RU", name: "Russland" },
  { code: "SE", name: "Schweden" },
  { code: "SI", name: "Slowenien" },
  { code: "SK", name: "Slowakei" },
  { code: "TR", name: "Türkei" },
  { code: "UA", name: "Ukraine" },
];

// Common currencies
export const CURRENCIES = [
  { code: "EUR", name: "Euro" },
  { code: "USD", name: "US-Dollar" },
  { code: "CHF", name: "Schweizer Franken" },
  { code: "GBP", name: "Britisches Pfund" },
  { code: "PLN", name: "Polnischer Złoty" },
  { code: "CZK", name: "Tschechische Krone" },
  { code: "SEK", name: "Schwedische Krone" },
  { code: "NOK", name: "Norwegische Krone" },
  { code: "DKK", name: "Dänische Krone" },
  { code: "HUF", name: "Ungarischer Forint" },
  { code: "RON", name: "Rumänischer Leu" },
  { code: "BGN", name: "Bulgarischer Lew" },
  { code: "JPY", name: "Japanischer Yen" },
  { code: "CNY", name: "Chinesischer Yuan" },
  { code: "RUB", name: "Russischer Rubel" },
  { code: "TRY", name: "Türkische Lira" },
  { code: "AUD", name: "Australischer Dollar" },
  { code: "CAD", name: "Kanadischer Dollar" },
  { code: "INR", name: "Indische Rupie" },
  { code: "BRL", name: "Brasilianischer Real" },
];

